services:
  laravel.test:
    image: 'laravelsail/php84-composer:latest'
    working_dir: /var/www/html
    ports:
      - '80:8000'
    volumes:
      - C:/Projects/FYP-Internship-main/internship-app:/var/www/html
    # Native Docker PHP commands to build the PostgreSQL driver from source!
    command: sh -c "apt-get update && apt-get install -y libpq-dev && docker-php-ext-install pdo_pgsql && composer install --ignore-platform-reqs && php artisan serve --host=0.0.0.0 --port=8000"
    depends_on:
      - pgsql

  pgsql:
    image: 'postgres:15-alpine'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'laravel'
      POSTGRES_USER: 'sail'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - 'fyp-postgres:/var/lib/postgresql/data'

volumes:
  fyp-postgres:
    driver: local